// Generated by scripts/build-theme.ts from global.css. Do not edit by hand.
import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

export const THEME = {
  light: {
    background: 'hsl(33 52.9% 96.7%)',
    foreground: 'hsl(32 13.1% 19.4%)',
    card: 'hsl(0 0% 100%)',
    cardForeground: 'hsl(32 13.1% 19.4%)',
    popover: 'hsl(0 0% 100%)',
    popoverForeground: 'hsl(32 13.1% 19.4%)',
    primary: 'hsl(18 100% 58.6%)',
    primaryForeground: 'hsl(0 0% 100%)',
    secondary: 'hsl(32 42.9% 93.1%)',
    secondaryForeground: 'hsl(38 13.3% 11.8%)',
    muted: 'hsl(32 42.9% 93.1%)',
    mutedForeground: 'hsl(34 12.7% 38.6%)',
    accent: 'hsl(207 69.6% 51%)',
    accentForeground: 'hsl(0 0% 100%)',
    destructive: 'hsl(0 63% 46.7%)',
    border: 'hsl(33 27.6% 79.4%)',
    input: 'hsl(33 27.6% 79.4%)',
    ring: 'hsl(18 100% 58.6%)',
    radius: '0.75rem',
  },
  dark: {
    background: 'hsl(30 13% 9%)',
    foreground: 'hsl(38 33.3% 85.9%)',
    card: 'hsl(38 13.3% 11.8%)',
    cardForeground: 'hsl(38 33.3% 85.9%)',
    popover: 'hsl(38 13.3% 11.8%)',
    popoverForeground: 'hsl(38 33.3% 85.9%)',
    primary: 'hsl(19 100% 63.9%)',
    primaryForeground: 'hsl(25 30% 7.8%)',
    secondary: 'hsl(30 17.6% 6.7%)',
    secondaryForeground: 'hsl(34 46.7% 94.1%)',
    muted: 'hsl(30 17.6% 6.7%)',
    mutedForeground: 'hsl(36 17.4% 63.9%)',
    accent: 'hsl(205 68.4% 55.3%)',
    accentForeground: 'hsl(0 0% 100%)',
    destructive: 'hsl(0 63% 46.7%)',
    border: 'hsl(33 15.8% 22.4%)',
    input: 'hsl(33 15.8% 22.4%)',
    ring: 'hsl(19 100% 63.9%)',
    radius: '0.75rem',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
