import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

// CSS var -> THEME key. Order defines emitted order. `radius` is raw (not hsl).
const TOKENS: Array<[cssVar: string, key: string]> = [
  ['background', 'background'],
  ['foreground', 'foreground'],
  ['card', 'card'],
  ['card-foreground', 'cardForeground'],
  ['popover', 'popover'],
  ['popover-foreground', 'popoverForeground'],
  ['primary', 'primary'],
  ['primary-foreground', 'primaryForeground'],
  ['secondary', 'secondary'],
  ['secondary-foreground', 'secondaryForeground'],
  ['muted', 'muted'],
  ['muted-foreground', 'mutedForeground'],
  ['accent', 'accent'],
  ['accent-foreground', 'accentForeground'],
  ['destructive', 'destructive'],
  ['border', 'border'],
  ['input', 'input'],
  ['ring', 'ring'],
  ['radius', 'radius'],
];

function parseBlock(css: string, selector: string): Record<string, string> {
  const start = css.indexOf(selector);
  if (start === -1) throw new Error(`build-theme: selector "${selector}" not found in global.css`);
  const open = css.indexOf('{', start);
  const close = css.indexOf('}', open);
  const body = css.slice(open + 1, close);
  const vars: Record<string, string> = {};
  for (const match of body.matchAll(/--([\w-]+):\s*([^;]+);/g)) {
    vars[match[1]] = match[2].trim();
  }
  return vars;
}

function emitScheme(vars: Record<string, string>): string {
  return TOKENS.map(([cssVar, key]) => {
    const raw = vars[cssVar];
    if (raw === undefined) {
      throw new Error(`build-theme: missing token "--${cssVar}" in global.css`);
    }
    const value = key === 'radius' ? raw : `hsl(${raw})`;
    return `    ${key}: '${value}',`;
  }).join('\n');
}

export function generateTheme(css: string): string {
  const light = parseBlock(css, ':root');
  // Dark only overrides a subset; unspecified tokens cascade from :root.
  const dark = { ...light, ...parseBlock(css, '.dark:root') };

  return `// Generated by scripts/build-theme.ts from global.css. Do not edit by hand.
import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

export const THEME = {
  light: {
${emitScheme(light)}
  },
  dark: {
${emitScheme(dark)}
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
`;
}

if (import.meta.main) {
  const root = process.cwd();
  const css = await readFile(resolve(root, 'global.css'), 'utf8');
  await writeFile(resolve(root, 'lib', 'theme.ts'), generateTheme(css), 'utf8');
  console.log('wrote lib/theme.ts from global.css');
}
